# Generated by Django 4.2.7 on 2023-12-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='document_proofs',
        ),
        migrations.AddField(
            model_name='tenant',
            name='document_proof',
            field=models.FileField(blank=True, null=True, upload_to='document_proofs/'),
        ),
    ]
